name: Release workflow

on:
  push:
    tags:
      - v[1-9]+.[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
          # TODO: add `v` to changelog versions
          # Then remote this and directly use `github.ref_name`.
          new_tag="${{ github.ref_name }}"
          new_tag="${new_tag:1}"
          echo "New Tag: ${new_tag}"
          # Extacts Keep a Changelog format. Credits https://stackoverflow.com/a/68119286
          awk -v ver="${new_tag}" '/^#+ \[/ { if (p) { exit }; if ($2 == "["ver"]") { p=1; next} } p && NF' "CHANGELOG.md" > rel_changelog.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: rel_changelog.txt
          name: "Release ${{ github.ref_name }}"
